### ISSUE TITLE
Buycycle 실행시 인증서가 필요한지 문의 드립니다.

### ISSUE THREAD

**Issue by mulmuri** [malchooni/buycycle#23]
안녕하세요. 튜토리얼 (https://opensource.buycycle.name/started.html ) 을 보고 설치하는 중에 있습니다.

최초 컴퓨터에서 인증서를 발급받은 후에 가이드를 따라 진행한 결과 잘 동작하였습니다.
이후 인증서가 없는 컴퓨터에서 같은 방식으로 진행하였을때는 쿼리문 작동시 오류가 나는 것처럼 보였습니다.
혹시 가이드에는 나와있지 않지만 인증서가 컴퓨터에 설치되어 있는게 필수인가요?

감사합니다.

**Comment by malchooni** [comment]
네 인증서가 필요합니다.

증권사 api사용시 인증을 인증서로 합니다

devcenter 설치 후 res파일도 다운 받으셔야 쿼리 목록들이 보입니다

기동시 res파일을 읽습니다
